apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc-rc
  labels:
    env: demo
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        env: demo  
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

